galaxy_info:
  author: Carlos León
  description: Docker
  company: Container Solutions
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - docker
    - swarm
    - swarmkit
    - dockerswarm
    - dockerswarmkit

dependencies: []
