---
- hosts: all
  become: yes
  become_user: root

  vars:
    networks:
      - internal
      - external
      - secure
      - backoffice

  tasks:
    # TODO: Only notify change when the networks are actually created
    - name: ensure networks are created
      shell: >
        if [ $(docker network ls | grep {{ item }} | wc -l) -eq 0 ]
          then
            docker network create -d weave {{ item }}
          else
            echo "noop"
        fi
      register: networkcreation
      with_items: "{{ networks }}"

    - name: ensure job file is present
      copy: src=files/service.nomad dest=/var/lib/nomad/jobs/service.nomad
      register: jobfile

    - name: check status of nomad job
      shell: nomad status | grep webservice | wc -l
      register: jobcheck
      changed_when: no

    - name: ensure nomad job is running
      command: nomad run /var/lib/nomad/jobs/service.nomad
      when: jobfile.changed or jobcheck.stdout == '0'
