---
- hosts: all
  become: yes
  become_user: root

  vars:
    - clusterstore: yes
    - consul_ip: 192.168.59.101

  roles:
    - roles/mongrelion.docker
    - roles/mongrelion.weave
    - roles/mongrelion.nomad

  tasks:
    - name: check for consul state
      command: docker ps -q -f name=consul
      register: consulcheck

    - name: check for weave state
      command: docker ps -q -f name=weave
      register: weavecheck

    - set_fact:
        should_runconsul: "{{ consulcheck.stdout_lines | length == 0 }}"
        should_weaveconsul: "{{ weavecheck.stdout_lines | length == 0 }}"

    - name: ensure consul is running
      command: docker run -d --name consul -p "8500:8500" progrium/consul -server -bootstrap
      when: should_runconsul

    - name: ensure weave is running
      command: weave launch
