---
- hosts: all
  become: yes
  become_user: root

  vars:
    - clusterstore: yes
    - consul_ip: 192.168.59.101
    - nomad_startonboot: yes

  roles:
    - roles/mongrelion.docker
    - roles/mongrelion.weave
    - roles/mongrelion.nomad

# We need to let Docker handlers to kick in before we call any Docker command
# Hence creating a new playset for checking Consul et all.
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: check for consul state
      command: docker ps -q -f name=consul
      register: consulcheck
      changed_when: no

    - name: check for weave state
      command: docker ps -q -f name=weave
      register: weavecheck
      changed_when: no

    - set_fact:
        should_runconsul: "{{ consulcheck.stdout_lines | length == 0 }}"
        should_runweave: "{{ weavecheck.stdout_lines | length == 0 }}"

    - name: ensure consul is running
      command: docker run -d --name consul -p "8500:8500" --restart always progrium/consul -server -bootstrap
      when: should_runconsul

    - name: ensure weave is running
      command: weave launch
      when: should_runweave
